ESLintルールの追加を行いました
takumi-13/Minesweeper pull request #23
Opened 2021-12-16 08:27 UTC by takumi-13

yarn lintでエラーが出ないため，恐らくできていると思います！

2021-12-17 05:17 UTC, hideto2112 requested changes
また、レビュー中ですが、お待たせしていると思うので、一旦コメント内容の確認をお願いします。

2021-12-17 05:17 UTC, hideto2112 commented on .github/workflows/deploy-client.yml
> +            key: client-yarn-${{ hashFiles('yarn.lock') }}
keyのインデントを変えてしまっているので、これではエラーがでます。
YAMLはインデントを使って階層構造を定義しているため、気をつけてください。
また、この修正箇所は、test.ymlでは修正していましたね。1箇所間違いに気が付いたら、同様のほかの箇所も確認する癖を付けると良いと思います。

2021-12-17 05:17 UTC, hideto2112 commented on pages/index.tsx
> +//console.log(boms)
デバッグ用のconsole.logをコメントアウトで残すのは、一般的ではないと思います。
MagiQでも使っていません。必要が生じたら、ローカルで検証する際に都度書いています。

2021-12-17 05:17 UTC, hideto2112 commented on utils/position.tsx
> +      b1 = b1 || posEquall(p1, p2)
ふと気になったのですが、こちら何をしているか説明していただけますか？
```js
b1 = b1
```

2021-12-17 05:17 UTC, hideto2112 commented on utils/bom.tsx
> +  //console.log(res)
別のファイルで書いたコメントと同様

2021-12-17 06:46 UTC, takumi-13 commented on utils/position.tsx
> +      b1 = b1 || posEquall(p1, p2)
ps1の各要素p1とps2の各要素p2に対して、一致するか判定し一致した際にはposEquall=trueとなるため、
b1にtrue || b1( = true) を代入して、それ以降のps2に対する繰り返しの間のb1をtrueにしています。
ps1とps2の並び順までは一致していない可能性を考慮してこのような実装にしました！
言われてみると少し不思議な実装な気もしてきました。

2021-12-17 07:01 UTC, takumi-13 commented on utils/position.tsx
> +      b1 = b1 || posEquall(p1, p2)
こちらについても修正を加えたほうがいいですよね？

2021-12-17 07:05 UTC, hideto2112 commented on utils/position.tsx
> +      b1 = b1 || posEquall(p1, p2)
回答ありがとうございます。
一旦このMRとしては閉じて、forEachの削減と合わせて別のIssueでの対応としましょう。

2021-12-17 07:14 UTC, takumi-13 commented on utils/position.tsx
> +      b1 = b1 || posEquall(p1, p2)
承知しました！

2021-12-17 08:27 UTC, hideto2112 requested changes
ご確認をお願いします。
コンポーネントとしての切り出しをお願いした部分は、一旦ファイルまで分割しなくても大丈夫です。
関数名だった部分がコンポーネント名になるので、名称の付け方を少し工夫してください。

2021-12-17 08:27 UTC, hideto2112 commented on components/boardHead.tsx
> +  if (gameState === 1) {
```ts
else if
```
とした方が自然かと思います。

2021-12-17 08:27 UTC, hideto2112 commented on pages/index.tsx
> +  const makeBoard = () => {
コンポーネントとして切り出してください。
```ts
const MakeBoard = ...
```

2021-12-17 08:27 UTC, hideto2112 commented on pages/index.tsx
> +  const makeHeader = () => {
コンポーネントとして切り出してください。

2021-12-17 08:27 UTC, hideto2112 commented on pages/index.tsx
> +          <Board>{makeBoard()}</Board>
コンポーネントとして読み込んでください。
```ts
<MakeHeader />
<Board><MakeBoard /></Board>>
```

2021-12-17 08:27 UTC, hideto2112 commented on components/boardMain.tsx
> +        key={`${x}-${y}`}
ループの部分ではないので、keyは不要かと思います。

2021-12-17 08:27 UTC, hideto2112 commented on components/boardMain.tsx
> +  const decidePushStyle = () => {
コンポーネントとして切り出してください。

2021-12-17 08:27 UTC, hideto2112 commented on components/boardMain.tsx
> +    decidePushStyle()
コンポーネントとして読み込んでください。

2021-12-20 03:22 UTC, hideto2112 requested changes
確認したい点があり、コメントしました。ご確認をお願いします。

2021-12-20 03:22 UTC, hideto2112 commented on components/boardMain.tsx
> +  const canPlayGame = gameState in [0, 1]
確認です。
```ts
gameState === 0 || gameState === -1
```
の部分を書き換えたと思いますが、表現したいことと合っていますか？

【参考リンク】
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/in
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

2021-12-20 04:00 UTC, takumi-13 commented on components/boardMain.tsx
> +  const canPlayGame = gameState in [0, 1]
間違えていました。
includesを使う場面であり、0,-1を判定したい部分であるのにも関わらず、0,1を判定していました。
見つけていただきありがとうございます。

修正しましたので、ご確認お願いします。

2021-12-20 05:55 UTC, hideto2112 approved these changes
修正ありがとうございました。

2021-12-20 05:56 UTC, merged