issue#26,27,28を取り組んだ
takumi-13/Minesweeper pull request #29
Opened 2021-12-21 07:49 UTC by takumi-13

下記3点の修正を行いました。
１．inの修正、
２．拡張子の修正 
３．コンポーネント関数内のJSXを複数書かないよう修正

ご確認よろしくお願いします。

2021-12-22 00:21 UTC, solufa commented on utils/updatePosition.ts
> +  return [0, 1, 2, 3, 4, 5, 6, 7, 8].includes(vs.x) && [0, 1, 2, 3, 4, 5, 6, 7, 8].includes(vs.y)
`[vs.x, vs.y].every(val => 0 <= val && val <= 8)`
とも書ける

2021-12-22 00:34 UTC, solufa commented on utils/bom.ts
> +  )
```ts
export const calBom = (x: number, y: number, boms: Pos[]) =>
  boms.map(elm => [elm.x - x, elm.y - y].map(Math.abs)).filter(vals => vals.every(v => [0, 1].includes(v))).length
```
これでも動く？

2021-12-22 00:39 UTC, solufa requested changes
次以降のチケットのために配列関数の書き方覚えておくといいです

2021-12-23 01:22 UTC, takumi-13 commented on utils/bom.ts
> +  )
動きました！

2021-12-23 01:22 UTC, takumi-13 commented on utils/updatePosition.ts
> +  return [0, 1, 2, 3, 4, 5, 6, 7, 8].includes(vs.x) && [0, 1, 2, 3, 4, 5, 6, 7, 8].includes(vs.y)
> 次以降のチケットのために配列関数の書き方覚えておくといいです

配列関数使えるように勉強しておきます。

2021-12-23 04:07 UTC, solufa commented on pages/index.tsx
> +    for (const element of res) {
すまぬ、ここはforEachが適切かも
ただuseState由来のboardを直接書き換えないようにするため
```ts
const newBoard: number[][] = JSON.parse(JSON.stringify(board))

res.forEach(......

setBoard(newBoard)
```

に変える

2021-12-23 04:08 UTC, solufa commented on pages/index.tsx
> +    const isBom = boms.find((el) => posEquall({ x: posX, y: posY }, el)) !== undefined
booleanが欲しいならsome/everyを使う

2021-12-23 04:39 UTC, solufa commented on utils/bom.ts
> +}
ランダムを扱う場合、配列メソッドで綺麗にかけないのはその通り

```ts
while (res.length < bomNum) {
  const pos = {}
  if (!res.some(p => p.x === pos.x && p.y === pos.y)) {
    res.push(pos)
  }
}
```
これだけでサクッと作れそう

2021-12-23 04:41 UTC, solufa commented on utils/updatePosition.ts
> +
```ts
const directions = [[-1, -1], [0, -1], [1, -1], ...
```
みたいな方向データを使えば以下まとまらないかな

2021-12-23 07:04 UTC, takumi-13 commented on pages/index.tsx
> +    for (const element of res) {
少しわかりづらい書き方になってしまっていて申し訳ないです。
`const newBoard: number[][] = JSON.parse(JSON.stringify(board))`
applyBoardでは引数として上記のコードを実行した後の配列をboardとして渡しています。
引数の名前を変更したいと思います！

2021-12-24 02:32 UTC, solufa commented on utils/updatePosition.ts
> +    }, [])
最小要素から生成するアプローチは良いですね
私は昔こんなコードを書きました

```ts
const directions = [-1, 0, 1]
  .flatMap((x, _, arr) => arr.map((y) => ({ x, y })))
  .filter((direction) => direction.x !== 0 || direction.y !== 0)
```

2021-12-24 02:36 UTC, solufa commented on utils/bom.ts
> +    res.push(pos)
引数で受け取った配列を破壊するデメリット>関数分割するメリット
なのでこの書き方なら上とまとめた方が良い
createBomから見て、resが変更されることは大変恐ろしい現象

2021-12-24 02:41 UTC, solufa commented on utils/updatePosition.ts
> +    }, [])
あ、別にこれ修正しなくていいです
あくまで参考

2021-12-24 02:46 UTC, solufa requested changes
細かいこと言うとキリがないからこのあたりで区切りにしようかー

2021-12-24 04:07 UTC, solufa approved these changes
おおむね良し

2021-12-24 04:07 UTC, merged