CSSの修正
takumi-13/Minesweeper pull request #33
Opened 2022-01-21 04:55 UTC by takumi-13

CSSを修正し、見た目を綺麗にしました。
主な修正点は下記のXXX点です。

1. ブロックの修正
2. 難易度選択の修正
3. 盤面の縁の修正
4. タイマーの表示位置の修正

詳細は画面のキャプチャと共に後述します。

2022-01-21 05:03 UTC, takumi-13 commented
1.ブロックの修正
- ブロックに影を追加
- ブロックの色を修正（押していないブロックは盤面の縁の色と統一、押したブロックはヘッダーの色と統一）
- 画像サイズの修正（全体的に小さく修正）
- 押したブロックの枠線の修正（色は影の色と統一、太さは提示されたリンクをもとに細く修正）

![2022-01-21-05-01-48](https://user-images.githubusercontent.com/43735224/150468996-47297b67-5e21-4784-b098-84d0886e7d4a.png)

2022-01-21 05:08 UTC, takumi-13 commented
2.難易度選択の修正
- ボタンとしてではなく、文字として表示するように修正
- 現在の難易度は黒字、それ以外の難易度は青く表示されるように修正
- 現在の難易度以外はホバー時に下線が引かれ、濃い青になるように修正

**通常時**
![2022-01-21-05-07-27](https://user-images.githubusercontent.com/43735224/150469437-35b76757-ed1c-4117-9425-d4ec07487cdc.png)

**ホバー時**
![2022-01-21-05-07-01](https://user-images.githubusercontent.com/43735224/150469436-e9df0d92-f957-4126-8dea-e2b98aae631a.png)

2022-01-21 05:11 UTC, takumi-13 commented
3.盤面の縁の修正
- 影の修正（色を押したブロックと統一）
- 色の修正（押していないブロックの色と統一）
- 細さを提示されたリンクを参考に修正

![2022-01-21-05-11-34](https://user-images.githubusercontent.com/43735224/150469739-04cb40b9-3503-4a74-81cb-f603e97334ba.png)

2022-01-21 05:13 UTC, takumi-13 commented
4.タイマーの表示位置の修正
- タイマーの上下中央を修正
![2022-01-21-05-13-23](https://user-images.githubusercontent.com/43735224/150469884-c5d0313e-a7ad-47d7-8218-85faa29e0faf.png)

2022-01-21 05:18 UTC, takumi-13 commented
5.盤面の表示倍率を変更
- ブロック数によって盤面の表示倍率を動的に変更するように修正

**初級**
![2022-01-21-05-15-58](https://user-images.githubusercontent.com/43735224/150470159-a22a94db-ec89-4d7a-9ec3-32698772e962.png)

**中級**
![2022-01-21-05-15-02](https://user-images.githubusercontent.com/43735224/150470084-ae885577-6df4-4f92-82d2-0b1c115396c6.png)

**上級**
![2022-01-21-05-14-49](https://user-images.githubusercontent.com/43735224/150470080-90cd4277-cc95-4e57-ae62-765be777bb6f.png)

**スペシャル（高さ：３０）**
![2022-01-21-05-14-55](https://user-images.githubusercontent.com/43735224/150470082-9e3f01e7-fc48-4664-bb02-bf36537f65c9.png)

**スペシャル（高さ：４０）**
![2022-01-21-05-15-18](https://user-images.githubusercontent.com/43735224/150470086-87f47414-cbaa-4df0-a7c2-f18fb49dfeb2.png)

2022-01-21 06:35 UTC, solufa requested changes
キャプチャ見る限り、顔がちょい潰れているような気がするけどどう？
あとブロックの数字の位置が中央じゃない

2022-01-27 08:57 UTC, takumi-13 commented
ご指摘いただいた、下記二点の修正を行いました。
・顔のつぶれの修正（ブロック全体に顔が表示されるように修正）
・ブロックの数字の位置をブロックの中央に移動

2022-01-27 08:58 UTC, takumi-13 commented
![2022-01-27-17-57-57](https://user-images.githubusercontent.com/43735224/151325623-83658a1e-cb81-4db7-ba4b-4f74b48d8551.png)

2022-01-27 09:02 UTC, solufa approved these changes
すごく本物に近くなった！

2022-01-27 09:02 UTC, merged