Make board
takumi-13/Minesweeper pull request #4
Opened 2021-11-15 09:25 UTC by takumi-13

BlockをPushedBlock(0-8用)とUnPushedBlockに分割して，それぞれ値を変更しました．
少し冗長な気もするため，Blockの継承（？）のような方法があればキーワードだけでも教えてください！

もしくは，Blockのままにして，background-colorの値だけを変更する方法もあるかと思ったのですが，調べても書き方がわかりませんでした．どうやればいいか教えて欲しいです．

![スクリーンショット 2021-11-15 18 22 40](https://user-images.githubusercontent.com/43735224/141755748-31320d72-48c0-4f71-adb8-2afd1bdf4994.png)

2021-11-15 10:20 UTC, solufa requested changes
おおむねいいですね
スタイルの冗長性を省く方法は「styled-components typescript props」あたりでググってみてください

2021-11-15 10:22 UTC, solufa commented
このページの右の欄にある「Linked issues」に今やってるIssueを紐づけてください
マージしたときに自動でCloseされる

2021-11-16 00:13 UTC, takumi-13 commented
Issueとのリンク，Blockを元にPushed Block, UnPushedBlockの作成の修正を行いました．
Reviewをお願いします．

2021-11-16 00:43 UTC, takumi-13 commented
すいません，Changes Requestの消し方ががわかりません．

2021-11-16 02:07 UTC, solufa commented on pages/index.tsx
> +                <PushedBlock key={`${x}-${y}`}> {num != 0 && num} </PushedBlock>
JS/TSは常にイコール3つで比較してください
イコール2つの意味がPythonとは違うのです

2021-11-16 02:14 UTC, takumi-13 commented on pages/index.tsx
> +                <PushedBlock key={`${x}-${y}`}> {num != 0 && num} </PushedBlock>
'=='だと変換されてしまうのですね．
把握しました．

2021-11-16 02:15 UTC, takumi-13 commented on pages/index.tsx
> +                <PushedBlock key={`${x}-${y}`}> {num != 0 && num} </PushedBlock>
該当箇所を変更しました．

2021-11-16 02:23 UTC, solufa approved these changes
LGTM

2021-11-16 02:24 UTC, merged